library(shiny)
library(shinydashboard)
library(ggplot2)
library(readxl)
library(leaflet)
library(leaflet.minicharts)
library(leaflet.extras)
library(mapview)
library(rgeos)
library(raster)
library(rgdal)
library(RColorBrewer)
library(maptools)
library(sp)
library(htmltools)
library(plyr)
library(hrbrthemes)

Notas <- read_excel("Notas.xlsx")


#Estudiar un poco estructura HTML para temas de estilo
shinyUI(dashboardPage(skin = "red",
  dashboardHeader(
    title=HTML(paste(strong("PAU VALENCIA"))),
    titleWidth = "7cm",
    dropdownMenu(type = "messages",
                 messageItem(
                   from = "Julio 2019",
                   message = "Incorporación notas Julio 2019",
                   icon = icon("bell"),
                   time = "1-3-2020"),
                 messageItem(
                   from = "Torrente",
                   message = "El próximo año contaremos con Torrente",
                   icon = icon("bullhorn"),
                   time = "29-02-2020"),
                 messageItem(
                   from = "Más Asignaturas",
                   message = "Añadimos más asignaturas",
                   icon = icon("comments"),
                   time = "28-02-2020"),
                 headerText = "Últimas Noticias"
    ),
    dropdownMenu(type = "notifications",
                 notificationItem(
                   text = "35 conexiones en el día de ayer",
                   icon("users"),
                   status = "success"),
                 notificationItem(
                   text = "Notas Algemesí recibidas ayer",
                   icon("paper-plane"),
                   status = "success"),
                 notificationItem(
                   text = "95% información disponible",
                   icon = icon("battery-three-quarters"),
                   status = "warning"),
                 headerText = "Información Reciente"
    ),
    dropdownMenu(type = "tasks", badgeStatus = "success",
                 taskItem(value = 90, color = "green",
                          "Selectivo Junio 2019"),
                 taskItem(value = 50, color = "aqua",
                          "Negociaciones Alicante-Castellón"),
                 taskItem(value = 75, color = "yellow",
                          "Distinción Público-Concertado/Privado"),
                 taskItem(value = 80, color = "red",
                          "Nivel Satisfacción"),
                 headerText = "Objetivos"
    )
  ), 
  dashboardSidebar(
    width = "7cm",
    sidebarMenu(
      id = "Variable",
      menuItem("Análisis 1 Variable", tabName="Variable1", icon=icon("chess-pawn"),
               menuSubItem("Curso", tabName="Variable_Curso", icon=icon("calendar")),
               menuSubItem("Municipio", tabName="Variable_Municipio", icon=icon("globe")),
               menuSubItem("Convocatoria", tabName="Variable_Conv", icon=icon("graduation-cap")),
               menuSubItem("Modalidad", tabName="Variable_ModalPAU", icon=icon("book-open")),
               menuSubItem("Tipo Centro", tabName="Variable_Ensenyanza",icon=icon("user")),
               startExpanded = TRUE),
      menuItem("Análisis 2 Variables", tabName="Variable2", icon=icon("chess-bishop"), badgeLabel="new", badgeColor = "blue"),
      menuItem("Análisis 3 Variables", tabName="Variable3", icon=icon("chess-knight")),
      menuItem("Mapas Representativos", tabName="Mapas", icon=icon("images"),
               menuSubItem("Mapa General", tabName="Mapa_General", icon=icon("atlas")),
               menuSubItem("Mapa Muncicipal", tabName="Mapa_Municipal", icon=icon("map-marked")),
               startExpanded = TRUE),
      menuItem("Mapas Comparativos", tabName="Heatmap", icon=icon("balance-scale"))
    )
  ),
  dashboardBody(
    tags$head(tags$style(HTML('
      .main-header .logo {
        font-family: "Georgia", Times, "Times New Roman", serif;
        font-weight: bold;
        font-size: 24px;
      }
    '))),
    tags$head(tags$style(HTML('.info-box {min-height: 75px;} .info-box-icon {height: 25px; line-height: 75px;} .info-box-content {padding-top: 0px; padding-bottom: 0px;}'))),
    tags$style(".nav-tabs {background-color: #FF5733;}
    .nav-tabs-custom .nav-tabs li.active {
    border-top-color: F7FF00;
    }"),
    
    tabItems(
      #FirstTabContent
      tabItem(tabName = "Variable_Curso",
              fluidRow(
                box(background = "aqua",
                    width = 6, 
                    height = 50,
                    selectInput("Nivel1","Curso",
                                list("2010" = "Nivel_2010",
                                     "2011" = "Nivel_2011",
                                     "2012" = "Nivel_2012",
                                     "2013" = "Nivel_2013",
                                     "2014" = "Nivel_2014",
                                     "2015" = "Nivel_2015",
                                     "2016" = "Nivel_2016",
                                     "2017" = "Nivel_2017",
                                     "2018" = "Nivel_2018",
                                     "2019" = "Nivel_2019"))),
                fluidRow(
                  infoBoxOutput("Box1",width = 5)
                )
              ),
              fluidRow(
                box(title = "RESUMEN", width = 6, height = 100, background = "green", solidHeader = TRUE, collapsible = TRUE, verbatimTextOutput("stats1"), tags$head(tags$style("#stats1{color:red; font-size:13px; font-style:italic;}"))),
                fluidRow(
                  infoBoxOutput("BoxBox1", width = 5)
                )
              ),
              fluidRow(
                tabBox(
                  width = 11,
                  title = "GRÁFICAS", id = "tabset1",
                  side = "left", height = "250px",
                  selected = "Histograma",
                  tabPanel("Histograma", plotOutput("hist1_1")),
                  tabPanel("Densidad", plotOutput("hist1_2")),
                  tabPanel("Hombres-Mujeres", plotOutput("hist1_3")),
                  tabPanel("Evolución Temporal", plotOutput("hist1_4")),
                  tabPanel("Evolución Media", plotOutput("hist1_5"))
                )
              )
      ),
      #SecondTabContent
      tabItem(tabName = "Variable_Municipio",
              fluidRow(
                box(background = "aqua",
                    width = 6,
                    height = 50,
                    selectInput("Nivel2","Municipio",
                                 list("Ademuz" = "Nivel_ADEMUZ",
                                      "Alaquas" = "Nivel_ALAQUAS",
                                      "Albaida" = "Nivel_ALBAIDA",
                                      "Albal" = "Nivel_ALBAL",
                                      "Alberic" = "Nivel_ALBERIC",
                                      "Alboraya" = "Nivel_ALBORAYA",
                                      "Alcasser" = "Nivel_ALCASSER",
                                      "Alfafar" = "Nivel_ALFAFAR",
                                      "Alginet" = "Nivel_ALGINET",
                                      "Almussafes" = "Nivel_ALMUSSAFES",
                                      "Ayora" = "Nivel_AYORA",
                                      "Benaguasil" = "Nivel_BENAGUASIL",
                                      "Benetusser" = "Nivel_BENETUSSER",
                                      "Benifaio" = "Nivel_BENIFAIO",
                                      "Benimamet" = "Nivel_BENIMAMET",
                                      "Betera" = "Nivel_BETERA",
                                      "Bocairent" = "Nivel_BOCAIRENT",
                                      "Buñol" = "Nivel_BUÑOL",
                                      "Burjassot" = "Nivel_BURJASSOT",
                                      "Campolivar" = "Nivel_CAMPOLIVAR",
                                      "Carcer" = "Nivel_CARCER",
                                      "Carlet" = "Nivel_CARLET",
                                      "Castello de Rugat" = "Nivel_CASTELLO_DE_RUGAT",
                                      "Catadau" = "Nivel_CATADAU",
                                      "Catarroja" = "Nivel_CATARROJA",
                                      "Cullera" = "Nivel_CULLERA",
                                      "El Puig" = "Nivel_EL_PUIG",
                                      "El Saler" = "Nivel_EL_SALER",
                                      "Godella" = "Nivel_GODELLA",
                                      "Guadassuar" = "Nivel_GUADASSUAR",
                                      "Jalance" = "Nivel_JALANCE",
                                      "L'Alcudia" = "Nivel_L'ALCUDIA",
                                      "L'Eliana" = "Nivel_LA_ELIANA",
                                      "L'Olleria" = "Nivel_L'OLLERIA",
                                      "La Cañada-Paterna" = "Nivel_LA_CAÑADA-PATERNA",
                                      "La Pobla de Farnals" = "Nivel_LA_POBLA_DE_FARNALS",
                                      "La Pobla de Vallbona" = "Nivel_LA_POBLA_DE_VALLBONA",
                                      "Lliria" = "Nivel_LLIRIA",
                                      "Massamagrell" = "Nivel_MASSAMAGRELL",
                                      "Massanassa" = "Nivel_MASSANASSA",
                                      "Mislata" = "Nivel_MISLATA",
                                      "Moncada" = "Nivel_MONCADA",
                                      "Montecañada-Paterna" = "Nivel_MONTECAÑADA-PATERNA",
                                      "Oliva" = "Nivel_OLIVA",
                                      "Ontinyent" = "Nivel_ONTINYENT",
                                      "Paterna" = "Nivel_PATERNA",
                                      "Picassent" = "Nivel_PICASSENT",
                                      "Puzol" = "Nivel_PUZOL",
                                      "Rafelbunyol" = "Nivel_RAFELBUNYOL",
                                      "Requena" = "Nivel_REQUENA",
                                      "S. Antonio Benageber" ="Nivel_S._ANTONIO_BENAGEBER",
                                      "Sedavi" = "Nivel_SEDAVI",
                                      "Silla" = "Nivel_SILLA",
                                      "Sueca" = "Nivel_SUECA",
                                      "Tavernes Blanques" = "Nivel_TAVERNES_BLANQUES",
                                      "Tavernes de Valldigna" = "Nivel_TAVERNES_DE_VALLDIGNA",
                                      "Turís" = "Nivel_TURÍS",
                                      "Utiel" = "Nivel_UTIEL",
                                      "Valencia" = "Nivel_VALENCIA",
                                      "Vilamarxant" = "Nivel_VILAMARXANT",
                                      "Villanueva de Castellón" = "Nivel_VILLANUEVA_CASTELLON",
                                      "Villar del Arzobispo" = "Nivel_VILLAR_DEL_ARZOBISPO"))),
                fluidRow(
                  infoBoxOutput("Box2", width = 5)
                )
              ),
              fluidRow(
                box(title = "RESUMEN", width = 6, height = 100, background = "green", solidHeader = TRUE, collapsible = TRUE, verbatimTextOutput("stats2"), tags$head(tags$style("#stats2{color:red; font-size:13px; font-style:italic;}"))),
                fluidRow(
                  infoBoxOutput("BoxBox2", width = 5)
                )
              ),
              fluidRow(
                tabBox(
                  width = 11,
                  title = "GRÁFICAS", id = "tabset2",
                  side = "left", height = "250px",
                  selected = "Histograma",
                  tabPanel("Histograma", plotOutput("hist2_1")),
                  tabPanel("Densidad", plotOutput("hist2_2")),
                  tabPanel("Hombres-Mujeres", plotOutput("hist2_3")),
                  tabPanel("Evolución Temporal", plotOutput("hist2_4")),
                  tabPanel("Evolución Media", plotOutput("hist2_5"))
                )
              )
      ),
      #ThirdTabContent
      tabItem(tabName = "Variable_Conv",
              fluidRow(
                box(background = "aqua",
                    width = 6,
                    height = 50,
                    selectInput("Nivel3","Convocatoria",
                                list("Junio" = "Nivel_JUNIO",
                                     "Julio" = "Nivel_JULIO"))),
                fluidRow(
                  infoBoxOutput("Box3", width = 5)
                )
              ),
              fluidRow(
                box(title = "RESUMEN", width = 6, height = 100, background = "green", solidHeader = TRUE, collapsible = TRUE, verbatimTextOutput("stats3"), tags$head(tags$style("#stats3{color:red; font-size:13px; font-style:italic;}"))),
                fluidRow(
                  infoBoxOutput("BoxBox3", width = 5)
                )
              ),
              fluidRow(
                tabBox(
                  width = 11,
                  title = "GRÁFICAS", id = "tabset3",
                  side = "left", height = "250px",
                  selected = "Histograma",
                  tabPanel("Histograma", plotOutput("hist3_1")),
                  tabPanel("Densidad", plotOutput("hist3_2")),
                  tabPanel("Hombres-Mujeres", plotOutput("hist3_3")),
                  tabPanel("Evolución Temporal", plotOutput("hist3_4")),
                  tabPanel("Evolución Media", plotOutput("hist3_5"))
                )
              )
      ),
      #FourthTabContent
      tabItem(tabName = "Variable_ModalPAU",
              fluidRow(
                box(background = "aqua",
                    width = 6, 
                    height = 50,
                    selectInput("Nivel4","Modalidad",
                                list("Artes" = "Nivel_Artes",
                                     "Ciencias y Tecnologia" = "Nivel_Ciencias_y_Tecnología",
                                     "Humanidades y Ciencias Sociales" = "Nivel_Humanidades_y_Ciencias_Sociales"))),
                fluidRow(
                  infoBoxOutput("Box4", width = 5)
                )
              ),
              fluidRow(
                box(title = "RESUMEN", width = 6, height = 100, background = "green", solidHeader = TRUE, collapsible = TRUE, verbatimTextOutput("stats4"), tags$head(tags$style("#stats4{color:red; font-size:13px; font-style:italic;}"))),
                fluidRow(
                  infoBoxOutput("BoxBox4", width = 5)
                )
              ),
              fluidRow(
                tabBox(
                  width = 11,
                  title = "GRÁFICAS", id = "tabset4",
                  side = "left", height = "250px",
                  selected = "Histograma",
                  tabPanel("Histograma", plotOutput("hist4_1")),
                  tabPanel("Densidad", plotOutput("hist4_2")),
                  tabPanel("Hombres-Mujeres", plotOutput("hist4_3")),
                  tabPanel("Evolución Temporal", plotOutput("hist4_4")),
                  tabPanel("Evolución Media", plotOutput("hist4_5"))
                )
              )
      ),
      #ExtraTabContent
      tabItem(tabName = "Variable_Ensenyanza",
              fluidRow(
                box(background = "aqua",
                    width = 6, 
                    height = 50,
                    selectInput("Nivel5","Tipo Centro",
                                list("Público" = "Nivel_PÚBLICO",
                                     "Concertado/Privado" = "Nivel_CONCERTADO/PRIVADO"))),
                fluidRow(
                  infoBoxOutput("Box5",width = 5)
                )
              ),
              fluidRow(
                box(title = "RESUMEN", width = 6, height = 100, background = "green", solidHeader = TRUE, collapsible = TRUE, verbatimTextOutput("stats5"), tags$head(tags$style("#stats5{color:red; font-size:13px; font-style:italic;}"))),
                fluidRow(
                  infoBoxOutput("BoxBox5", width = 5)
                )
              ),
              fluidRow(
                tabBox(
                  width = 11,
                  title = "GRÁFICAS", id = "tabset5",
                  side = "left", height = "250px",
                  selected = "Histograma",
                  tabPanel("Histograma", plotOutput("hist5_1")),
                  tabPanel("Densidad", plotOutput("hist5_2")),
                  tabPanel("Hombres-Mujeres", plotOutput("hist5_3")),
                  tabPanel("Evolucion Temporal", plotOutput("hist5_4")),
                  tabPanel("Evolucion Media", plotOutput("hist5_5"))
                )
              )
      ),
      #FifthTabContent
      tabItem(tabName = "Variable2",
              fluidRow(
              box(background = "aqua",
                  height = 75,
                  selectInput("Variable21","Variable 1",
                              list("Curso" = "Variable21_Curso",
                                   "Municipio" = "Variable21_Municipio",
                                   "Convocatoria" = "Variable21_Conv",
                                   "Modalidad" = "Variable21_ModalPAU",
                                   "Tipo Centro" = "Variable21_Ensenyanza"))),
              conditionalPanel(
                condition="input.Variable21=='Variable21_Curso'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel21Curso","Nivel 1",
                                list("2010" = "Nivel21_2010",
                                     "2011" = "Nivel21_2011",
                                     "2012" = "Nivel21_2012",
                                     "2013" = "Nivel21_2013",
                                     "2014" = "Nivel21_2014",
                                     "2015" = "Nivel21_2015",
                                     "2016" = "Nivel21_2016",
                                     "2017" = "Nivel21_2017",
                                     "2018" = "Nivel21_2018",
                                     "2019" = "Nivel21_2019")))),
              conditionalPanel(
                condition="input.Variable21=='Variable21_Municipio'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel21Municipio","Nivel 1",
                                list("Ademuz" = "Nivel21_ADEMUZ",
                                     "Alaquas" = "Nivel21_ALAQUAS",
                                     "Albaida" = "Nivel21_ALBAIDA",
                                     "Albal" = "Nivel21_ALBAL",
                                     "Alberic" = "Nivel21_ALBERIC",
                                     "Alboraya" = "Nivel21_ALBORAYA",
                                     "Alcasser" = "Nivel21_ALCASSER",
                                     "Alfafar" = "Nivel21_ALFAFAR",
                                     "Alginet" = "Nivel21_ALGINET",
                                     "Almussafes" = "Nivel21_ALMUSSAFES",
                                     "Ayora" = "Nivel21_AYORA",
                                     "Benaguasil" = "Nivel21_BENAGUASIL",
                                     "Benetusser" = "Nivel21_BENETUSSER",
                                     "Benifaio" = "Nivel21_BENIFAIO",
                                     "Benimamet" = "Nivel21_BENIMAMET",
                                     "Betera" = "Nivel21_BETERA",
                                     "Bocairent" = "Nivel21_BOCAIRENT",
                                     "Buñol" = "Nivel21_BUÑOL",
                                     "Burjassot" = "Nivel21_BURJASSOT",
                                     "Campolivar" = "Nivel21_CAMPOLIVAR",
                                     "Carcer" = "Nivel21_CARCER",
                                     "Carlet" = "Nivel21_CARLET",
                                     "Castello de Rugat" = "Nivel21_CASTELLO_DE_RUGAT",
                                     "Catadau" = "Nivel21_CATADAU",
                                     "Catarroja" = "Nivel21_CATARROJA",
                                     "Cullera" = "Nivel21_CULLERA",
                                     "El Puig" = "Nivel21_EL_PUIG",
                                     "El Saler" = "Nivel21_EL_SALER",
                                     "Godella" = "Nivel21_GODELLA",
                                     "Guadassuar" = "Nivel21_GUADASSUAR",
                                     "Jalance" = "Nivel21_JALANCE",
                                     "L'Alcudia" = "Nivel21_L'ALCUDIA",
                                     "L'Eliana" = "Nivel21_LA_ELIANA",
                                     "L'Olleria" = "Nivel21_L'OLLERIA",
                                     "La Cañada-Paterna" = "Nivel21_LA_CAÑADA-PATERNA",
                                     "La Pobla de Farnals" = "Nivel21_LA_POBLA_DE_FARNALS",
                                     "La Pobla de Vallbona" = "Nivel21_LA_POBLA_DE_VALLBONA",
                                     "Lliria" = "Nivel21_LLIRIA",
                                     "Massamagrell" = "Nivel21_MASSAMAGRELL",
                                     "Massanassa" = "Nivel21_MASSANASSA",
                                     "Mislata" = "Nivel21_MISLATA",
                                     "Moncada" = "Nivel21_MONCADA",
                                     "Montecañada-Paterna" = "Nivel21_MONTECAÑADA-PATERNA",
                                     "Oliva" = "Nivel21_OLIVA",
                                     "Ontinyent" = "Nivel21_ONTINYENT",
                                     "Paterna" = "Nivel21_PATERNA",
                                     "Picassent" = "Nivel21_PICASSENT",
                                     "Puzol" = "Nivel21_PUZOL",
                                     "Rafelbunyol" = "Nivel21_RAFELBUNYOL",
                                     "Requena" = "Nivel21_REQUENA",
                                     "S. Antonio Benageber" ="Nivel21_S._ANTONIO_BENAGEBER",
                                     "Sedavi" = "Nivel21_SEDAVI",
                                     "Silla" = "Nivel21_SILLA",
                                     "Sueca" = "Nivel21_SUECA",
                                     "Tavernes Blanques" = "Nivel21_TAVERNES_BLANQUES",
                                     "Tavernes de Valldigna" = "Nivel21_TAVERNES_DE_VALLDIGNA",
                                     "Turís" = "Nivel21_TURÍS",
                                     "Utiel" = "Nivel21_UTIEL",
                                     "Valencia" = "Nivel21_VALENCIA",
                                     "Vilamarxant" = "Nivel21_VILAMARXANT",
                                     "Villanueva de Castellón" = "Nivel21_VILLANUEVA_CASTELLON",
                                     "Villar del Arzobispo" = "Nivel21_VILLAR_DEL_ARZOBISPO")))),
              conditionalPanel(
                condition="input.Variable21=='Variable21_Conv'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel21Convocatoria","Nivel 1",
                                list("Junio" = "Nivel21_JUNIO",
                                     "Julio" = "Nivel21_JULIO")))),
              conditionalPanel(
                condition="input.Variable21=='Variable21_ModalPAU'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel21Modalidad","Nivel 1",
                                list("Artes" = "Nivel21_Artes",
                                     "Ciencias y Tecnologia" = "Nivel21_Ciencias_y_Tecnología",
                                     "Humanidades y Ciencias Sociales" = "Nivel21_Humanidades_y_Ciencias_Sociales")))),
              conditionalPanel(
                condition="input.Variable21=='Variable21_Ensenyanza'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel21TipoCentro","Nivel 1",
                                list("Público" = "Nivel21_PÚBLICO",
                                     "Concertado/Privado" = "Nivel21_CONCERTADO/PRIVADO"))))
              ),
              fluidRow(
              box(background = "aqua",
                  height = 75,
                  selectInput("Variable22","Variable 2",
                              list("Curso" = "Variable22_Curso",
                                   "Municipio" = "Variable22_Municipio",
                                   "Convocatoria" = "Variable22_Conv",
                                   "Modalidad" = "Variable22_ModalPAU",
                                   "Tipo Centro" = "Variable22_Ensenyanza"))),
              conditionalPanel(
                condition="input.Variable22=='Variable22_Curso'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel22Curso","Nivel 2",
                                list("2010" = "Nivel22_2010",
                                     "2011" = "Nivel22_2011",
                                     "2012" = "Nivel22_2012",
                                     "2013" = "Nivel22_2013",
                                     "2014" = "Nivel22_2014",
                                     "2015" = "Nivel22_2015",
                                     "2016" = "Nivel22_2016",
                                     "2017" = "Nivel22_2017",
                                     "2018" = "Nivel22_2018",
                                     "2019" = "Nivel22_2019")))),
              conditionalPanel(
                condition="input.Variable22=='Variable22_Municipio'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel22Municipio","Nivel 2",
                                list("Ademuz" = "Nivel22_ADEMUZ",
                                     "Alaquas" = "Nivel22_ALAQUAS",
                                     "Albaida" = "Nivel22_ALBAIDA",
                                     "Albal" = "Nivel22_ALBAL",
                                     "Alberic" = "Nivel22_ALBERIC",
                                     "Alboraya" = "Nivel22_ALBORAYA",
                                     "Alcasser" = "Nivel22_ALCASSER",
                                     "Alfafar" = "Nivel22_ALFAFAR",
                                     "Alginet" = "Nivel22_ALGINET",
                                     "Almussafes" = "Nivel22_ALMUSSAFES",
                                     "Ayora" = "Nivel22_AYORA",
                                     "Benaguasil" = "Nivel22_BENAGUASIL",
                                     "Benetusser" = "Nivel22_BENETUSSER",
                                     "Benifaio" = "Nivel22_BENIFAIO",
                                     "Benimamet" = "Nivel22_BENIMAMET",
                                     "Betera" = "Nivel22_BETERA",
                                     "Bocairent" = "Nivel22_BOCAIRENT",
                                     "Buñol" = "Nivel22_BUÑOL",
                                     "Burjassot" = "Nivel22_BURJASSOT",
                                     "Campolivar" = "Nivel22_CAMPOLIVAR",
                                     "Carcer" = "Nivel22_CARCER",
                                     "Carlet" = "Nivel22_CARLET",
                                     "Castello de Rugat" = "Nivel22_CASTELLO_DE_RUGAT",
                                     "Catadau" = "Nivel22_CATADAU",
                                     "Catarroja" = "Nivel22_CATARROJA",
                                     "Cullera" = "Nivel22_CULLERA",
                                     "El Puig" = "Nivel22_EL_PUIG",
                                     "El Saler" = "Nivel22_EL_SALER",
                                     "Godella" = "Nivel22_GODELLA",
                                     "Guadassuar" = "Nivel22_GUADASSUAR",
                                     "Jalance" = "Nivel22_JALANCE",
                                     "L'Alcudia" = "Nivel22_L'ALCUDIA",
                                     "L'Eliana" = "Nivel22_LA_ELIANA",
                                     "L'Olleria" = "Nivel22_L'OLLERIA",
                                     "La Cañada-Paterna" = "Nivel22_LA_CAÑADA-PATERNA",
                                     "La Pobla de Farnals" = "Nivel22_LA_POBLA_DE_FARNALS",
                                     "La Pobla de Vallbona" = "Nivel22_LA_POBLA_DE_VALLBONA",
                                     "Lliria" = "Nivel22_LLIRIA",
                                     "Massamagrell" = "Nivel22_MASSAMAGRELL",
                                     "Massanassa" = "Nivel22_MASSANASSA",
                                     "Mislata" = "Nivel22_MISLATA",
                                     "Moncada" = "Nivel22_MONCADA",
                                     "Montecañada-Paterna" = "Nivel22_MONTECAÑADA-PATERNA",
                                     "Oliva" = "Nivel22_OLIVA",
                                     "Ontinyent" = "Nivel22_ONTINYENT",
                                     "Paterna" = "Nivel22_PATERNA",
                                     "Picassent" = "Nivel22_PICASSENT",
                                     "Puzol" = "Nivel22_PUZOL",
                                     "Rafelbunyol" = "Nivel22_RAFELBUNYOL",
                                     "Requena" = "Nivel22_REQUENA",
                                     "S. Antonio Benageber" ="Nivel22_S._ANTONIO_BENAGEBER",
                                     "Sedavi" = "Nivel22_SEDAVI",
                                     "Silla" = "Nivel22_SILLA",
                                     "Sueca" = "Nivel22_SUECA",
                                     "Tavernes Blanques" = "Nivel22_TAVERNES_BLANQUES",
                                     "Tavernes de Valldigna" = "Nivel22_TAVERNES_DE_VALLDIGNA",
                                     "Turís" = "Nivel22_TURÍS",
                                     "Utiel" = "Nivel22_UTIEL",
                                     "Valencia" = "Nivel22_VALENCIA",
                                     "Vilamarxant" = "Nivel22_VILAMARXANT",
                                     "Villanueva de Castellón" = "Nivel22_VILLANUEVA_CASTELLON",
                                     "Villar del Arzobispo" = "Nivel22_VILLAR_DEL_ARZOBISPO")))),
              conditionalPanel(
                condition="input.Variable22=='Variable22_Conv'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel22Convocatoria","Nivel 2",
                                list("Junio" = "Nivel22_JUNIO",
                                     "Julio" = "Nivel22_JULIO")))),
              conditionalPanel(
                condition="input.Variable22=='Variable22_ModalPAU'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel22Modalidad","Nivel 2",
                                list("Artes" = "Nivel22_Artes",
                                     "Ciencias y Tecnologia" = "Nivel22_Ciencias_y_Tecnología",
                                     "Humanidades y Ciencias Sociales" = "Nivel22_Humanidades_y_Ciencias_Sociales")))),
              conditionalPanel(
                condition="input.Variable22=='Variable22_Ensenyanza'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel22TipoCentro","Nivel 2",
                                list("Público" = "Nivel22_PÚBLICO",
                                     "Concertado/Privado" = "Nivel22_CONCERTADO/PRIVADO"))))
              ),
              fluidRow(
                infoBoxOutput("Box21", width = 3),
                fluidRow(
                  infoBoxOutput("BoxBox21", width = 3),
                  fluidRow(
                    box(title = "RESUMEN", width = 5, height = 100, background = "green", solidHeader = TRUE, collapsible = TRUE, verbatimTextOutput("stats21"), tags$head(tags$style("#stats21{color:red; font-size:13px; font-style:italic;}")))
                  )
                )
              ),
              fluidRow(
                tabBox(
                  width = 11,
                  title = "GRÁFICAS", id = "tabset5",
                  side = "left", height = "250px",
                  selected = "Histograma",
                  tabPanel("Histograma", plotOutput("hist22_1")),
                  tabPanel("Densidad", plotOutput("hist22_2")),
                  tabPanel("Hombres-Mujeres", plotOutput("hist22_3"))
                )
              )
      ),
      #SixthTabContent
      tabItem(tabName = "Variable3",
              fluidRow(
              box(background = "aqua",
                  height = 75,
                  selectInput("Variable31","Variable 1",
                              list("Curso" = "Variable31_Curso",
                                   "Municipio" = "Variable31_Municipio",
                                   "Convocatoria" = "Variable31_Conv",
                                   "Modalidad" = "Variable31_ModalPAU",
                                   "Tipo Centro" = "Variable31_Ensenyanza"))),
              conditionalPanel(
                condition="input.Variable31=='Variable31_Curso'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel31Curso","Nivel 1",
                                list("2010" = "Nivel31_2010",
                                     "2011" = "Nivel31_2011",
                                     "2012" = "Nivel31_2012",
                                     "2013" = "Nivel31_2013",
                                     "2014" = "Nivel31_2014",
                                     "2015" = "Nivel31_2015",
                                     "2016" = "Nivel31_2016",
                                     "2017" = "Nivel31_2017",
                                     "2018" = "Nivel31_2018",
                                     "2019" = "Nivel31_2019")))),
              conditionalPanel(
                condition="input.Variable31=='Variable31_Municipio'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel31Municipio","Nivel 1",
                                list("Ademuz" = "Nivel31_ADEMUZ",
                                     "Alaquas" = "Nivel31_ALAQUAS",
                                     "Albaida" = "Nivel31_ALBAIDA",
                                     "Albal" = "Nivel31_ALBAL",
                                     "Alberic" = "Nivel31_ALBERIC",
                                     "Alboraya" = "Nivel31_ALBORAYA",
                                     "Alcasser" = "Nivel31_ALCASSER",
                                     "Alfafar" = "Nivel31_ALFAFAR",
                                     "Alginet" = "Nivel31_ALGINET",
                                     "Almussafes" = "Nivel31_ALMUSSAFES",
                                     "Ayora" = "Nivel31_AYORA",
                                     "Benaguasil" = "Nivel31_BENAGUASIL",
                                     "Benetusser" = "Nivel31_BENETUSSER",
                                     "Benifaio" = "Nivel31_BENIFAIO",
                                     "Benimamet" = "Nivel31_BENIMAMET",
                                     "Betera" = "Nivel31_BETERA",
                                     "Bocairent" = "Nivel31_BOCAIRENT",
                                     "Buñol" = "Nivel31_BUÑOL",
                                     "Burjassot" = "Nivel31_BURJASSOT",
                                     "Campolivar" = "Nivel31_CAMPOLIVAR",
                                     "Carcer" = "Nivel31_CARCER",
                                     "Carlet" = "Nivel31_CARLET",
                                     "Castello de Rugat" = "Nivel31_CASTELLO_DE_RUGAT",
                                     "Catadau" = "Nivel31_CATADAU",
                                     "Catarroja" = "Nivel31_CATARROJA",
                                     "Cullera" = "Nivel31_CULLERA",
                                     "El Puig" = "Nivel31_EL_PUIG",
                                     "El Saler" = "Nivel31_EL_SALER",
                                     "Godella" = "Nivel31_GODELLA",
                                     "Guadassuar" = "Nivel31_GUADASSUAR",
                                     "Jalance" = "Nivel31_JALANCE",
                                     "L'Alcudia" = "Nivel31_L'ALCUDIA",
                                     "L'Eliana" = "Nivel31_LA_ELIANA",
                                     "L'Olleria" = "Nivel31_L'OLLERIA",
                                     "La Cañada-Paterna" = "Nivel31_LA_CAÑADA-PATERNA",
                                     "La Pobla de Farnals" = "Nivel31_LA_POBLA_DE_FARNALS",
                                     "La Pobla de Vallbona" = "Nivel31_LA_POBLA_DE_VALLBONA",
                                     "Lliria" = "Nivel31_LLIRIA",
                                     "Massamagrell" = "Nivel31_MASSAMAGRELL",
                                     "Massanassa" = "Nivel31_MASSANASSA",
                                     "Mislata" = "Nivel31_MISLATA",
                                     "Moncada" = "Nivel31_MONCADA",
                                     "Montecañada-Paterna" = "Nivel31_MONTECAÑADA-PATERNA",
                                     "Oliva" = "Nivel31_OLIVA",
                                     "Ontinyent" = "Nivel31_ONTINYENT",
                                     "Paterna" = "Nivel31_PATERNA",
                                     "Picassent" = "Nivel31_PICASSENT",
                                     "Puzol" = "Nivel31_PUZOL",
                                     "Rafelbunyol" = "Nivel31_RAFELBUNYOL",
                                     "Requena" = "Nivel31_REQUENA",
                                     "S. Antonio Benageber" ="Nivel31_S._ANTONIO_BENAGEBER",
                                     "Sedavi" = "Nivel31_SEDAVI",
                                     "Silla" = "Nivel31_SILLA",
                                     "Sueca" = "Nivel31_SUECA",
                                     "Tavernes Blanques" = "Nivel31_TAVERNES_BLANQUES",
                                     "Tavernes de Valldigna" = "Nivel31_TAVERNES_DE_VALLDIGNA",
                                     "Turís" = "Nivel31_TURÍS",
                                     "Utiel" = "Nivel31_UTIEL",
                                     "Valencia" = "Nivel31_VALENCIA",
                                     "Vilamarxant" = "Nivel31_VILAMARXANT",
                                     "Villanueva de Castellón" = "Nivel31_VILLANUEVA_CASTELLON",
                                     "Villar del Arzobispo" = "Nivel31_VILLAR_DEL_ARZOBISPO")))),
              conditionalPanel(
                condition="input.Variable31=='Variable31_Conv'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel31Convocatoria","Nivel 1",
                                list("Junio" = "Nivel31_JUNIO",
                                     "Julio" = "Nivel31_JULIO")))),
              conditionalPanel(
                condition="input.Variable31=='Variable31_ModalPAU'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel31Modalidad","Nivel 1",
                                list("Artes" = "Nivel31_Artes",
                                     "Ciencias y Tecnologia" = "Nivel31_Ciencias_y_Tecnología",
                                     "Humanidades y Ciencias Sociales" = "Nivel31_Humanidades_y_Ciencias_Sociales")))),
              conditionalPanel(
                condition="input.Variable31=='Variable31_Ensenyanza'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel31TipoCentro","Nivel 1",
                                list("Público" = "Nivel31_PÚBLICO",
                                     "Concertado/Privado" = "Nivel31_CONCERTADO/PRIVADO"))))
              ),
              fluidRow(
              box(background = "aqua",
                  height = 75,
                  selectInput("Variable32","Variable 2",
                              list("Curso" = "Variable32_Curso",
                                   "Municipio" = "Variable32_Municipio",
                                   "Convocatoria" = "Variable32_Conv",
                                   "Modalidad" = "Variable32_ModalPAU",
                                   "Tipo Centro" = "Variable32_Ensenyanza"))),
              conditionalPanel(
                condition="input.Variable32=='Variable32_Curso'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel32Curso","Nivel 2",
                                list("2010" = "Nivel32_2010",
                                     "2011" = "Nivel32_2011",
                                     "2012" = "Nivel32_2012",
                                     "2013" = "Nivel32_2013",
                                     "2014" = "Nivel32_2014",
                                     "2015" = "Nivel32_2015",
                                     "2016" = "Nivel32_2016",
                                     "2017" = "Nivel32_2017",
                                     "2018" = "Nivel32_2018",
                                     "2019" = "Nivel32_2019")))),
              conditionalPanel(
                condition="input.Variable32=='Variable32_Municipio'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel32Municipio","Nivel 2",
                                list("Ademuz" = "Nivel32_ADEMUZ",
                                     "Alaquas" = "Nivel32_ALAQUAS",
                                     "Albaida" = "Nivel32_ALBAIDA",
                                     "Albal" = "Nivel32_ALBAL",
                                     "Alberic" = "Nivel32_ALBERIC",
                                     "Alboraya" = "Nivel32_ALBORAYA",
                                     "Alcasser" = "Nivel32_ALCASSER",
                                     "Alfafar" = "Nivel32_ALFAFAR",
                                     "Alginet" = "Nivel32_ALGINET",
                                     "Almussafes" = "Nivel32_ALMUSSAFES",
                                     "Ayora" = "Nivel32_AYORA",
                                     "Benaguasil" = "Nivel32_BENAGUASIL",
                                     "Benetusser" = "Nivel32_BENETUSSER",
                                     "Benifaio" = "Nivel32_BENIFAIO",
                                     "Benimamet" = "Nivel32_BENIMAMET",
                                     "Betera" = "Nivel32_BETERA",
                                     "Bocairent" = "Nivel32_BOCAIRENT",
                                     "Buñol" = "Nivel32_BUÑOL",
                                     "Burjassot" = "Nivel32_BURJASSOT",
                                     "Campolivar" = "Nivel32_CAMPOLIVAR",
                                     "Carcer" = "Nivel32_CARCER",
                                     "Carlet" = "Nivel32_CARLET",
                                     "Castello de Rugat" = "Nivel32_CASTELLO_DE_RUGAT",
                                     "Catadau" = "Nivel32_CATADAU",
                                     "Catarroja" = "Nivel32_CATARROJA",
                                     "Cullera" = "Nivel32_CULLERA",
                                     "El Puig" = "Nivel32_EL_PUIG",
                                     "El Saler" = "Nivel32_EL_SALER",
                                     "Godella" = "Nivel32_GODELLA",
                                     "Guadassuar" = "Nivel32_GUADASSUAR",
                                     "Jalance" = "Nivel32_JALANCE",
                                     "L'Alcudia" = "Nivel32_L'ALCUDIA",
                                     "L'Eliana" = "Nivel32_LA_ELIANA",
                                     "L'Olleria" = "Nivel32_L'OLLERIA",
                                     "La Cañada-Paterna" = "Nivel32_LA_CAÑADA-PATERNA",
                                     "La Pobla de Farnals" = "Nivel32_LA_POBLA_DE_FARNALS",
                                     "La Pobla de Vallbona" = "Nivel32_LA_POBLA_DE_VALLBONA",
                                     "Lliria" = "Nivel32_LLIRIA",
                                     "Massamagrell" = "Nivel32_MASSAMAGRELL",
                                     "Massanassa" = "Nivel32_MASSANASSA",
                                     "Mislata" = "Nivel32_MISLATA",
                                     "Moncada" = "Nivel32_MONCADA",
                                     "Montecañada-Paterna" = "Nivel32_MONTECAÑADA-PATERNA",
                                     "Oliva" = "Nivel32_OLIVA",
                                     "Ontinyent" = "Nivel32_ONTINYENT",
                                     "Paterna" = "Nivel32_PATERNA",
                                     "Picassent" = "Nivel32_PICASSENT",
                                     "Puzol" = "Nivel32_PUZOL",
                                     "Rafelbunyol" = "Nivel32_RAFELBUNYOL",
                                     "Requena" = "Nivel32_REQUENA",
                                     "S. Antonio Benageber" ="Nivel32_S._ANTONIO_BENAGEBER",
                                     "Sedavi" = "Nivel32_SEDAVI",
                                     "Silla" = "Nivel32_SILLA",
                                     "Sueca" = "Nivel32_SUECA",
                                     "Tavernes Blanques" = "Nivel32_TAVERNES_BLANQUES",
                                     "Tavernes de Valldigna" = "Nivel32_TAVERNES_DE_VALLDIGNA",
                                     "Turís" = "Nivel32_TURÍS",
                                     "Utiel" = "Nivel32_UTIEL",
                                     "Valencia" = "Nivel32_VALENCIA",
                                     "Vilamarxant" = "Nivel32_VILAMARXANT",
                                     "Villanueva de Castellón" = "Nivel32_VILLANUEVA_CASTELLON",
                                     "Villar del Arzobispo" = "Nivel32_VILLAR_DEL_ARZOBISPO")))),
              conditionalPanel(
                condition="input.Variable32=='Variable32_Conv'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel32Convocatoria","Nivel 2",
                                list("Junio" = "Nivel32_JUNIO",
                                     "Julio" = "Nivel32_JULIO")))),
              conditionalPanel(
                condition="input.Variable32=='Variable32_ModalPAU'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel32Modalidad","Nivel 2",
                                list("Artes" = "Nivel32_Artes",
                                     "Ciencias y Tecnologia" = "Nivel32_Ciencias_y_Tecnología",
                                     "Humanidades y Ciencias Sociales" = "Nivel32_Humanidades_y_Ciencias_Sociales")))),
              conditionalPanel(
                condition="input.Variable32=='Variable32_Ensenyanza'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel32TipoCentro","Nivel 2",
                                list("Público" = "Nivel32_PÚBLICO",
                                     "Concertado/Privado" = "Nivel32_CONCERTADO/PRIVADO"))))
              ),
              fluidRow(
              box(background = "aqua",
                  height = 75,
                  selectInput("Variable33","Variable 3",
                              list("Curso" = "Variable33_Curso",
                                   "Municipio" = "Variable33_Municipio",
                                   "Convocatoria" = "Variable33_Conv",
                                   "Modalidad" = "Variable33_ModalPAU",
                                   "Tipo Centro" = "Variable33_Ensenyanza"))),
              conditionalPanel(
                condition="input.Variable33=='Variable33_Curso'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel33Curso","Nivel 3",
                                list("2010" = "Nivel33_2010",
                                     "2011" = "Nivel33_2011",
                                     "2012" = "Nivel33_2012",
                                     "2013" = "Nivel33_2013",
                                     "2014" = "Nivel33_2014",
                                     "2015" = "Nivel33_2015",
                                     "2016" = "Nivel33_2016",
                                     "2017" = "Nivel33_2017",
                                     "2018" = "Nivel33_2018",
                                     "2019" = "Nivel33_2019")))),
              conditionalPanel(
                condition="input.Variable33=='Variable33_Municipio'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel33Municipio","Nivel 3",
                                list("Ademuz" = "Nivel33_ADEMUZ",
                                     "Alaquas" = "Nivel33_ALAQUAS",
                                     "Albaida" = "Nivel33_ALBAIDA",
                                     "Albal" = "Nivel33_ALBAL",
                                     "Alberic" = "Nivel33_ALBERIC",
                                     "Alboraya" = "Nivel33_ALBORAYA",
                                     "Alcasser" = "Nivel33_ALCASSER",
                                     "Alfafar" = "Nivel33_ALFAFAR",
                                     "Alginet" = "Nivel33_ALGINET",
                                     "Almussafes" = "Nivel33_ALMUSSAFES",
                                     "Ayora" = "Nivel33_AYORA",
                                     "Benaguasil" = "Nivel33_BENAGUASIL",
                                     "Benetusser" = "Nivel33_BENETUSSER",
                                     "Benifaio" = "Nivel33_BENIFAIO",
                                     "Benimamet" = "Nivel33_BENIMAMET",
                                     "Betera" = "Nivel33_BETERA",
                                     "Bocairent" = "Nivel33_BOCAIRENT",
                                     "Buñol" = "Nivel33_BUÑOL",
                                     "Burjassot" = "Nivel33_BURJASSOT",
                                     "Campolivar" = "Nivel33_CAMPOLIVAR",
                                     "Carcer" = "Nivel33_CARCER",
                                     "Carlet" = "Nivel33_CARLET",
                                     "Castello de Rugat" = "Nivel33_CASTELLO_DE_RUGAT",
                                     "Catadau" = "Nivel33_CATADAU",
                                     "Catarroja" = "Nivel33_CATARROJA",
                                     "Cullera" = "Nivel33_CULLERA",
                                     "El Puig" = "Nivel33_EL_PUIG",
                                     "El Saler" = "Nivel33_EL_SALER",
                                     "Godella" = "Nivel33_GODELLA",
                                     "Guadassuar" = "Nivel33_GUADASSUAR",
                                     "Jalance" = "Nivel33_JALANCE",
                                     "L'Alcudia" = "Nivel33_L'ALCUDIA",
                                     "L'Eliana" = "Nivel33_LA_ELIANA",
                                     "L'Olleria" = "Nivel33_L'OLLERIA",
                                     "La Cañada-Paterna" = "Nivel33_LA_CAÑADA-PATERNA",
                                     "La Pobla de Farnals" = "Nivel33_LA_POBLA_DE_FARNALS",
                                     "La Pobla de Vallbona" = "Nivel33_LA_POBLA_DE_VALLBONA",
                                     "Lliria" = "Nivel33_LLIRIA",
                                     "Massamagrell" = "Nivel33_MASSAMAGRELL",
                                     "Massanassa" = "Nivel33_MASSANASSA",
                                     "Mislata" = "Nivel33_MISLATA",
                                     "Moncada" = "Nivel33_MONCADA",
                                     "Montecañada-Paterna" = "Nivel33_MONTECAÑADA-PATERNA",
                                     "Oliva" = "Nivel33_OLIVA",
                                     "Ontinyent" = "Nivel33_ONTINYENT",
                                     "Paterna" = "Nivel33_PATERNA",
                                     "Picassent" = "Nivel33_PICASSENT",
                                     "Puzol" = "Nivel33_PUZOL",
                                     "Rafelbunyol" = "Nivel33_RAFELBUNYOL",
                                     "Requena" = "Nivel33_REQUENA",
                                     "S. Antonio Benageber" ="Nivel33_S._ANTONIO_BENAGEBER",
                                     "Sedavi" = "Nivel33_SEDAVI",
                                     "Silla" = "Nivel33_SILLA",
                                     "Sueca" = "Nivel33_SUECA",
                                     "Tavernes Blanques" = "Nivel33_TAVERNES_BLANQUES",
                                     "Tavernes de Valldigna" = "Nivel33_TAVERNES_DE_VALLDIGNA",
                                     "Turís" = "Nivel33_TURÍS",
                                     "Utiel" = "Nivel33_UTIEL",
                                     "Valencia" = "Nivel33_VALENCIA",
                                     "Vilamarxant" = "Nivel33_VILAMARXANT",
                                     "Villanueva de Castellón" = "Nivel33_VILLANUEVA_CASTELLON",
                                     "Villar del Arzobispo" = "Nivel33_VILLAR_DEL_ARZOBISPO")))),
              conditionalPanel(
                condition="input.Variable33=='Variable33_Conv'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel33Convocatoria","Nivel 3",
                                list("Junio" = "Nivel33_JUNIO",
                                     "Julio" = "Nivel33_JULIO")))),
              conditionalPanel(
                condition="input.Variable33=='Variable33_ModalPAU'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel33Modalidad","Nivel 3",
                                list("Artes" = "Nivel33_Artes",
                                     "Ciencias y Tecnologia" = "Nivel33_Ciencias_y_Tecnología",
                                     "Humanidades y Ciencias Sociales" = "Nivel33_Humanidades_y_Ciencias_Sociales")))),
              conditionalPanel(
                condition="input.Variable33=='Variable33_Ensenyanza'",
                box(background = "aqua",
                    height = 75,
                    selectInput("Nivel33TipoCentro","Nivel 3",
                                list("Público" = "Nivel33_PÚBLICO",
                                     "Concertado/Privado" = "Nivel33_CONCERTADO/PRIVADO"))))
              ),
              fluidRow(
                infoBoxOutput("Box31", width = 3),
                fluidRow(
                  infoBoxOutput("BoxBox31", width = 3),
                fluidRow(
                  box(title = "RESUMEN", width = 5, height = 100, background = "green", solidHeader = TRUE, collapsible = TRUE, verbatimTextOutput("stats31"), tags$head(tags$style("#stats31{color:red; font-size:13px; font-style:italic;}")))
                )
                )
              ),
              fluidRow(
                tabBox(
                  width = 11,
                  title = "GRÁFICAS", id = "tabset6",
                  side = "left", height = "250px",
                  selected = "Histograma",
                  tabPanel("Histograma", plotOutput("hist33_1")),
                  tabPanel("Densidad", plotOutput("hist33_2")),
                  tabPanel("Hombres-Mujeres", plotOutput("hist33_3"))
                )
              )
      ),
      #Map1TabContent
      tabItem(tabName = "Mapa_General",
             fluidRow(
                box(background = "aqua",
                    width = 6, 
                    height = 50,
                    selectInput("MapaGeneral1","Curso",
                           list("General" = "Clase_General",
                                "2010" = "Clase_2010",
                                "2011" = "Clase_2011",
                                "2012" = "Clase_2012",
                                "2013" = "Clase_2013",
                                "2014" = "Clase_2014",
                                "2015" = "Clase_2015",
                                "2016" = "Clase_2016",
                                "2017" = "Clase_2017",
                                "2018" = "Clase_2018",
                                "2019" = "Clase_2019"))),
                      ),
              mainPanel(
                leafletOutput("MapaGeneral",height=680,width=1150)
              )
      ),
      #Map2TabContent
      tabItem(tabName = "Mapa_Municipal",
              fluidRow(
                box(background = "aqua",
                    width = 6, 
                    height = 50,
                    selectInput("MapaMunicipal1","Municipio",
                                list("Global" = "Clase_Global",
                                     "Ademuz" = "Clase_ADEMUZ",
                                     "Alaquas" = "Clase_ALAQUAS",
                                     "Albaida" = "Clase_ALBAIDA",
                                     "Albal" = "Clase_ALBAL",
                                     "Alberic" = "Clase_ALBERIC",
                                     "Alboraya" = "Clase_ALBORAYA",
                                     "Alcasser" = "Clase_ALCASSER",
                                     "Alfafar" = "Clase_ALFAFAR",
                                     "Alginet" = "Clase_ALGINET",
                                     "Almussafes" = "Clase_ALMUSSAFES",
                                     "Ayora" = "Clase_AYORA",
                                     "Benaguasil" = "Clase_BENAGUASIL",
                                     "Benetusser" = "Clase_BENETUSSER",
                                     "Benifaio" = "Clase_BENIFAIO",
                                     "Benimamet" = "Clase_BENIMAMET",
                                     "Betera" = "Clase_BETERA",
                                     "Bocairent" = "Clase_BOCAIRENT",
                                     "Buñol" = "Clase_BUÑOL",
                                     "Burjassot" = "Clase_BURJASSOT",
                                     "Campolivar" = "Clase_CAMPOLIVAR",
                                     "Carcer" = "Clase_CARCER",
                                     "Carlet" = "Clase_CARLET",
                                     "Castello de Rugat" = "Clase_CASTELLO_DE_RUGAT",
                                     "Catadau" = "Clase_CATADAU",
                                     "Catarroja" = "Clase_CATARROJA",
                                     "Cullera" = "Clase_CULLERA",
                                     "El Puig" = "Clase_EL_PUIG",
                                     "El Saler" = "Clase_EL_SALER",
                                     "Godella" = "Clase_GODELLA",
                                     "Guadassuar" = "Clase_GUADASSUAR",
                                     "Jalance" = "Clase_JALANCE",
                                     "L'Alcudia" = "Clase_L'ALCUDIA",
                                     "L'Eliana" = "Clase_LA_ELIANA",
                                     "L'Olleria" = "Clase_L'OLLERIA",
                                     "La Cañada-Paterna" = "Clase_LA_CAÑADA-PATERNA",
                                     "La Pobla de Farnals" = "Clase_LA_POBLA_DE_FARNALS",
                                     "La Pobla de Vallbona" = "Clase_LA_POBLA_DE_VALLBONA",
                                     "Lliria" = "Clase_LLIRIA",
                                     "Massamagrell" = "Clase_MASSAMAGRELL",
                                     "Massanassa" = "Clase_MASSANASSA",
                                     "Mislata" = "Clase_MISLATA",
                                     "Moncada" = "Clase_MONCADA",
                                     "Montecañada-Paterna" = "Clase_MONTECAÑADA-PATERNA",
                                     "Oliva" = "Clase_OLIVA",
                                     "Ontinyent" = "Clase_ONTINYENT",
                                     "Paterna" = "Clase_PATERNA",
                                     "Picassent" = "Clase_PICASSENT",
                                     "Puzol" = "Clase_PUZOL",
                                     "Rafelbunyol" = "Clase_RAFELBUNYOL",
                                     "Requena" = "Clase_REQUENA",
                                     "S. Antonio Benageber" ="Clase_S._ANTONIO_BENAGEBER",
                                     "Sedavi" = "Clase_SEDAVI",
                                     "Silla" = "Clase_SILLA",
                                     "Sueca" = "Clase_SUECA",
                                     "Tavernes Blanques" = "Clase_TAVERNES_BLANQUES",
                                     "Tavernes de Valldigna" = "Clase_TAVERNES_DE_VALLDIGNA",
                                     "Turís" = "Clase_TURÍS",
                                     "Utiel" = "Clase_UTIEL",
                                     "Valencia" = "Clase_VALENCIA",
                                     "Vilamarxant" = "Clase_VILAMARXANT",
                                     "Villanueva de Castellón" = "Clase_VILLANUEVA_CASTELLON",
                                     "Villar del Arzobispo" = "Clase_VILLAR_DEL_ARZOBISPO"))),
                      ),
              mainPanel(
                leafletOutput("MapaMunicipal",height=680,width=1150)
              )
      ),
      #Last TabContent
      tabItem(tabName = "Heatmap",
              fluidRow(
                box(background = "aqua",
                    width = 6,
                    height = 50,
                    selectInput("Categoria1","Categoria",
                                list("Curso" = "Categoria_Curso",
                                     "Municipio" = "Categoria_Municipio")))
              ),
              mainPanel(
                plotOutput("MapaCalor",height=750,width=1300)
              )
      )
  ))
))